# import jsonpath as jsonpath
from jsonpath import jsonpath

jsondata={
  "category_list": {
    "can_create_category": False,
    "can_create_topic": False,
    "draft": ' ',
    "draft_key": "new_topic",
    "draft_sequence":'',
    "categories": [
      {
        "id": 16,
        "name": "霍格沃兹测试学院公众号",
        "color": "0088CC",
        "text_color": "FFFFFF",
        "slug": "hogwarts",
        "topic_count": 25,
        "post_count": 203,
        "position": 0,
        "description": "霍格沃兹测试学院官方文章",
        "description_text": "霍格沃兹测试学院官方文章",
        "description_excerpt": "霍格沃兹测试学院官方文章",
        "topic_url": "/t/topic/236",
        "read_restricted": False,
        "permission": ' ',
        "notification_level": 1,
        "topic_template": "",
        "has_children": False,
        "sort_order": "",
        "sort_ascending": ' ',
        "show_subcategory_list": False,
        "num_featured_topics": 3,
        "default_view": "",
        "subcategory_list_style": "rows_with_featured_topics",
        "default_top_period": "all",
        "default_list_filter": "all",
        "minimum_required_tags": 0,
        "navigate_to_first_post_after_read": False,
        "topics_day": 1,
        "topics_week": 4,
        "topics_month": 6,
        "topics_year": 25,
        "topics_all_time": 25,
        "uploaded_logo": ' ',
        "uploaded_background": ' '
      },
      {
        "id": 6,
        "name": "霍格沃兹测试学院校内交流",
        "color": "0088CC",
        "text_color": "FFFFFF",
        "slug": "hogwartsinner",
        "topic_count": 78,
        "post_count": 190,
        "position": 1,
        "description": "霍格沃兹测试学院所有学员的公共交流区，非学员仅可阅读",
        "description_text": "霍格沃兹测试学院所有学员的公共交流区，非学员仅可阅读",
        "description_excerpt": "霍格沃兹测试学院所有学员的公共交流区，非学员仅可阅读",
        "topic_url": "/t/topic/14",
        "read_restricted": False,
        "permission": ' ',
        "notification_level": 1,
        "topic_template": "",
        "has_children": False,
        "sort_order": "",
        "sort_ascending": ' ',
        "show_subcategory_list": False,
        "num_featured_topics": 3,
        "default_view": "",
        "subcategory_list_style": "rows_with_featured_topics",
        "default_top_period": "all",
        "default_list_filter": "all",
        "minimum_required_tags": 0,
        "navigate_to_first_post_after_read": False,
        "topics_day": 4,
        "topics_week": 5,
        "topics_month": 16,
        "topics_year": 78,
        "topics_all_time": 78,
        "uploaded_logo": ' ',
        "uploaded_background": ' '
      },
      {
        "id": 22,
        "name": "霍格沃兹答疑区",
        "color": "0088CC",
        "text_color": "FFFFFF",
        "slug": "",
        "topic_count": 319,
        "post_count": 1235,
        "position": 2,
        "description": ' ',
        "description_text": ' ',
        "description_excerpt": ' ',
        "topic_url": "/t/topic/597",
        "read_restricted": False,
        "permission": ' ',
        "notification_level": 1,
        "topic_template": "",
        "has_children": True,
        "sort_order": "",
        "sort_ascending": ' ',
        "show_subcategory_list": False,
        "num_featured_topics": 3,
        "default_view": "",
        "subcategory_list_style": "rows_with_featured_topics",
        "default_top_period": "all",
        "default_list_filter": "all",
        "minimum_required_tags": 0,
        "navigate_to_first_post_after_read": False,
        "topics_day": 10,
        "topics_week": 35,
        "topics_month": 106,
        "topics_year": 360,
        "topics_all_time": 360,
        "subcategory_ids": [
          8
        ],
        "uploaded_logo": ' ',
        "uploaded_background": ' '
      },
      {
        "id": 14,
        "name": "霍格沃兹测试学院教务处",
        "color": "0088CC",
        "text_color": "FFFFFF",
        "slug": "hogwartsoffice",
        "topic_count": 7,
        "post_count": 7,
        "position": 4,
        "description": "霍格沃兹测试学院官方政策公布",
        "description_text": "霍格沃兹测试学院官方政策公布",
        "description_excerpt": "霍格沃兹测试学院官方政策公布",
        "topic_url": "/t/topic/227",
        "read_restricted": False,
        "permission": ' ',
        "notification_level": 1,
        "topic_template": "",
        "has_children": False,
        "sort_order": "",
        "sort_ascending": ' ',
        "show_subcategory_list": False,
        "num_featured_topics": 3,
        "default_view": "",
        "subcategory_list_style": "rows_with_featured_topics",
        "default_top_period": "all",
        "default_list_filter": "all",
        "minimum_required_tags": 0,
        "navigate_to_first_post_after_read": False,
        "topics_day": 0,
        "topics_week": 1,
        "topics_month": 1,
        "topics_year": 7,
        "topics_all_time": 7,
        "uploaded_logo": ' ',
        "uploaded_background": ' '
      },
      {
        "id": 1,
        "name": "未分类",
        "color": "0088CC",
        "text_color": "FFFFFF",
        "slug": "uncategorized",
        "topic_count": 73,
        "post_count": 191,
        "position": 15,
        "description": "不需要分类或者不适合放在现有的任何分类中的主题。",
        "description_text": "不需要分类或者不适合放在现有的任何分类中的主题。",
        "description_excerpt": "不需要分类或者不适合放在现有的任何分类中的主题。",
        "topic_url": ' ',
        "read_restricted": False,
        "permission": ' ',
        "notification_level": 1,
        "topic_template": ' ',
        "has_children": False,
        "sort_order": ' ',
        "sort_ascending": ' ',
        "show_subcategory_list": False,
        "num_featured_topics": 3,
        "default_view": ' ',
        "subcategory_list_style": "rows_with_featured_topics",
        "default_top_period": "all",
        "default_list_filter": "all",
        "minimum_required_tags": 0,
        "navigate_to_first_post_after_read": False,
        "topics_day": 0,
        "topics_week": 3,
        "topics_month": 18,
        "topics_year": 73,
        "topics_all_time": 73,
        "is_uncategorized": True,
        "uploaded_logo": ' ',
        "uploaded_background": ' '
      },
      {
        "id": 2,
        "name": "Site Feedback",
        "color": "808281",
        "text_color": "FFFFFF",
        "slug": "site-feedback",
        "topic_count": 2,
        "post_count": 6,
        "position": 18,
        "description": "Discussion about this site, its organization, how it works, and how we can improve it.",
        "description_text": "Discussion about this site, its organization, how it works, and how we can improve it.",
        "description_excerpt": "Discussion about this site, its organization, how it works, and how we can improve it.",
        "topic_url": "/t/about-the-site-feedback-category/1",
        "read_restricted": False,
        "permission": ' ',
        "notification_level": 1,
        "topic_template": ' ',
        "has_children": False,
        "sort_order": ' ',
        "sort_ascending": ' ',
        "show_subcategory_list": False,
        "num_featured_topics": 3,
        "default_view": ' ',
        "subcategory_list_style": "rows_with_featured_topics",
        "default_top_period": "all",
        "default_list_filter": "all",
        "minimum_required_tags": 0,
        "navigate_to_first_post_after_read": False,
        "topics_day": 0,
        "topics_week": 0,
        "topics_month": 0,
        "topics_year": 2,
        "topics_all_time": 2,
        "uploaded_logo": ' ',
        "uploaded_background": ' '
      },
      {
        "id": 17,
        "name": "开源项目",
        "color": "0088CC",
        "text_color": "FFFFFF",
        "slug": "opensource",
        "topic_count": 106,
        "post_count": 118,
        "position": 19,
        "description": "开源项目交流与维护",
        "description_text": "开源项目交流与维护",
        "description_excerpt": "开源项目交流与维护",
        "topic_url": "/t/topic/314",
        "read_restricted": False,
        "permission": ' ',
        "notification_level": 1,
        "topic_template": ' ',
        "has_children": True,
        "sort_order": ' ',
        "sort_ascending": ' ',
        "show_subcategory_list": False,
        "num_featured_topics": 3,
        "default_view": ' ',
        "subcategory_list_style": "rows_with_featured_topics",
        "default_top_period": "all",
        "default_list_filter": "all",
        "minimum_required_tags": 0,
        "navigate_to_first_post_after_read": False,
        "topics_day": 0,
        "topics_week": 0,
        "topics_month": 0,
        "topics_year": 117,
        "topics_all_time": 117,
        "subcategory_ids": [
          24,
          23
        ],
        "uploaded_logo": ' ',
        "uploaded_background": ' '
      },
      {
        "id": 29,
        "name": "读书圈",
        "color": "25AAE2",
        "text_color": "FFFFFF",
        "slug": "book",
        "topic_count": 3,
        "post_count": 12,
        "position": 27,
        "description": "学院一向倡导多读书多学习。<br>\n所以开设了此区，欢迎喜欢读书的朋友来分享、交流自己看过的经典书籍。",
        "description_text": "学院一向倡导多读书多学习。\n所以开设了此区，欢迎喜欢读书的朋友来分享、交流自己看过的经典书籍。",
        "description_excerpt": "学院一向倡导多读书多学习。 \n所以开设了此区，欢迎喜欢读书的朋友来分享、交流自己看过的经典书籍。",
        "topic_url": "/t/topic/2425",
        "read_restricted": False,
        "permission": ' ',
        "notification_level": 1,
        "topic_template": "",
        "has_children": False,
        "sort_order": ' ',
        "sort_ascending": ' ',
        "show_subcategory_list": False,
        "num_featured_topics": 3,
        "default_view": ' ',
        "subcategory_list_style": "rows_with_featured_topics",
        "default_top_period": "all",
        "default_list_filter": "all",
        "minimum_required_tags": 0,
        "navigate_to_first_post_after_read": False,
        "topics_day": 0,
        "topics_week": 0,
        "topics_month": 0,
        "topics_year": 3,
        "topics_all_time": 3,
        "uploaded_logo": ' ',
        "uploaded_background": ' '
      },
      {
        "id": 30,
        "name": "测试开发教材讨论区",
        "color": "0E76BD",
        "text_color": "FFFFFF",
        "slug": "",
        "topic_count": 2,
        "post_count": 8,
        "position": 28,
        "description": ' ',
        "description_text": ' ',
        "description_excerpt": ' ',
        "topic_url": "/t/topic/2463",
        "read_restricted": False,
        "permission": ' ',
        "notification_level": 1,
        "topic_template": ' ',
        "has_children": False,
        "sort_order": ' ',
        "sort_ascending": ' ',
        "show_subcategory_list": False,
        "num_featured_topics": 3,
        "default_view": ' ',
        "subcategory_list_style": "rows_with_featured_topics",
        "default_top_period": "all",
        "default_list_filter": "all",
        "minimum_required_tags": 0,
        "navigate_to_first_post_after_read": False,
        "topics_day": 0,
        "topics_week": 0,
        "topics_month": 1,
        "topics_year": 2,
        "topics_all_time": 2,
        "uploaded_logo": ' ',
        "uploaded_background": ' '
      },
      {
        "id": 31,
        "name": "职位内推",
        "color": "12A89D",
        "text_color": "FFFFFF",
        "slug": "job",
        "topic_count": 99,
        "post_count": 101,
        "position": 29,
        "description": "名企职位推荐，成功入职可获得奖学金。",
        "description_text": "名企职位推荐，成功入职可获得奖学金。",
        "description_excerpt": "名企职位推荐，成功入职可获得奖学金。",
        "topic_url": "/t/topic/2678",
        "read_restricted": False,
        "permission": ' ',
        "notification_level": 1,
        "topic_template": "## 城市 - 公司名称 - 职位名称 \n\n\n## 岗位职责\n\n## 岗位要求 \n\n## 薪资范围 \n\n## 工作地点及福利  \n\n## 投递方式\n-  想内推该职位的同学，可以发送简历到hrbp@ceshiren.com， 备注自己的所在班级",
        "has_children": False,
        "sort_order": "",
        "sort_ascending": ' ',
        "show_subcategory_list": False,
        "num_featured_topics": 3,
        "default_view": "",
        "subcategory_list_style": "rows_with_featured_topics",
        "default_top_period": "all",
        "default_list_filter": "all",
        "minimum_required_tags": 0,
        "navigate_to_first_post_after_read": False,
        "topics_day": 1,
        "topics_week": 7,
        "topics_month": 45,
        "topics_year": 99,
        "topics_all_time": 99,
        "uploaded_logo": ' ',
        "uploaded_background": ' '
      },
      {
        "id": 40,
        "name": "兴趣爱好交流",
        "color": "0088CC",
        "text_color": "FFFFFF",
        "slug": "",
        "topic_count": 0,
        "post_count": 0,
        "position": 38,
        "description": ' ',
        "description_text": ' ',
        "description_excerpt": ' ',
        "topic_url": "/t/topic/2805",
        "read_restricted": False,
        "permission": ' ',
        "notification_level": 1,
        "topic_template": ' ',
        "has_children": True,
        "sort_order": ' ',
        "sort_ascending": ' ',
        "show_subcategory_list": False,
        "num_featured_topics": 3,
        "default_view": ' ',
        "subcategory_list_style": "rows_with_featured_topics",
        "default_top_period": "all",
        "default_list_filter": "all",
        "minimum_required_tags": 0,
        "navigate_to_first_post_after_read": False,
        "topics_day": 0,
        "topics_week": 0,
        "topics_month": 0,
        "topics_year": 0,
        "topics_all_time": 0,
        "subcategory_ids": [
          41
        ],
        "uploaded_logo": ' ',
        "uploaded_background": ' '
      },
      {
        "id": 43,
        "name": "测试课程",
        "color": "0088CC",
        "text_color": "FFFFFF",
        "slug": "ke",
        "topic_count": 1,
        "post_count": 1,
        "position": 41,
        "description": ' ',
        "description_text": ' ',
        "description_excerpt": ' ',
        "topic_url": "/t/topic/3114",
        "read_restricted": False,
        "permission": ' ',
        "notification_level": 1,
        "topic_template": ' ',
        "has_children": False,
        "sort_order": ' ',
        "sort_ascending": ' ',
        "show_subcategory_list": False,
        "num_featured_topics": 3,
        "default_view": ' ',
        "subcategory_list_style": "rows_with_featured_topics",
        "default_top_period": "all",
        "default_list_filter": "all",
        "minimum_required_tags": 0,
        "navigate_to_first_post_after_read": False,
        "topics_day": 0,
        "topics_week": 0,
        "topics_month": 1,
        "topics_year": 1,
        "topics_all_time": 1,
        "uploaded_logo": ' ',
        "uploaded_background": ' '
      }
    ]
  }
}
# jsonpath
def test_jsonpath():
    print(jsonpath(jsondata, '$..name'))
    print(jsonpath(jsondata,'$..name')[0])  # 取出第一个name
